# -*- coding: utf-8 -*-
"""welcome.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/github/instillai/TensorFlow-Course/blob/master/codes/ipython/0-welcome/welcome.ipynb
"""

# Import tensorflow
import tensorflow as tf

# Check version
print("Tensorflow version: ", tf.__version__)

# Test TensorFlow for cuda availibility
'''
首先明确，要成功使用tensorflow-gpu版本，需要三个东西。

CUDA：是NVIDIA发明了一种并行计算平台和编程模型。通过利用图形处理单元（GPU）的强大功能，它可以显着提高计算性能。
cuDNN：是用于深度神经网络的GPU加速原语库。
Tensorflow-gpu：是一个用于高性能数值计算的开源软件库（GPU版本）。
'''
print("Tensorflow is built with CUDA: ", tf.test.is_built_with_cuda())

# Check devices
print("All devices: ", tf.config.experimental_list_devices())
# print("GPU devices: ", tf.config.experimental_list_devices(device_type='GPU'))

# Print a randomly generated tensor
# tf.math.reduce_sum: https://www.tensorflow.org/api_docs/python/tf/math/reduce_sum
# tf.random.normal: https://www.tensorflow.org/api_docs/python/tf/random/normal
print("randomly generated tensor",tf.math.reduce_sum(tf.random.normal([1, 10])))